version: '3.8'

services:
  # 1. Prometheus (Thu thập dữ liệu)
  prometheus:
    image: prom/prometheus:latest
    container_name: monitor-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # 2. Grafana (Hiển thị biểu đồ)
  grafana:
    image: grafana/grafana:latest
    container_name: monitor-grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Pass mặc định là admin

  # 3. Node Exporter (Lấy thông tin CPU/RAM/Disk của máy thật)
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: monitor-node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'

  # 4. Custom Python Exporter (Chạy script Python như một service)
  log-exporter:
    build: .  # Sẽ build từ Dockerfile tại thư mục hiện tại
    container_name: monitor-log-exporter
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /var/log/auth.log:/var/log/auth.log:ro # Mount file log thật vào container
