global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # Gọi theo tên service trong docker-compose

  - job_name: 'python-log-exporter'
    static_configs:
      - targets: ['log-exporter:8000']
  - job_name: 'python-ssh-exporter'
    static_configs:
      - targets: ['log-exporter:8000']  # Dùng tên service trong docker-compose
